package com.imagine.livelingo;

import android.Manifest; import android.app.Activity; import android.content.Intent; import android.content.pm.PackageManager; import android.graphics.Color; import android.graphics.Typeface; import android.graphics.drawable.GradientDrawable; import android.net.Uri; import android.os.Bundle; import android.os.Handler; import android.os.Looper; import android.view.Gravity; import android.view.View; import android.widget.*; import androidx.core.content.FileProvider;
import com.imagine.livelingo.core.SpokenDiff; import java.io.File; import java.util.ArrayList; import java.util.List;

public class MainActivity extends Activity implements LiveSpeechRecognizer.Listener {
    private static final int REQ=7; private TextView status,sourceText,translatedText,detected,headset; private Button mainButton,debugButton; private Spinner inputSpinner,targetSpinner;
    private LiveSpeechRecognizer speech; private TranslationEngine translator; private OfflineSpeaker speaker; private final SpokenDiff spokenDiff=new SpokenDiff(2); private boolean active;
    private final Handler debounce=new Handler(Looper.getMainLooper()); private Runnable pendingTranslation; private long translationSeq=0; private String manualInput="auto"; private DebugTrace trace;
    @Override protected void onCreate(Bundle b){super.onCreate(b);trace=new DebugTrace(this);getWindow().setStatusBarColor(0xFFF4F5F8);buildUi();translator=new TranslationEngine();speaker=new OfflineSpeaker(this,s->{status.setText(s);trace.log("TTS_STATUS",s);});speech=new LiveSpeechRecognizer(this,this);mainButton.setOnClickListener(v->toggle());debugButton.setOnClickListener(v->shareTrace());inputSpinner.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){manualInput=LanguageCatalog.inputCodeForDisplay((String)inputSpinner.getSelectedItem());trace.log("UI_INPUT_LANGUAGE",manualInput);speech.setInputLanguage(manualInput);detected.setText("auto".equals(manualInput)?"Автоопределение языка":"Говорит: "+LanguageCatalog.displayForCode(manualInput));spokenDiff.reset();translationSeq++;}public void onNothingSelected(android.widget.AdapterView<?> p){}});targetSpinner.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){String c=LanguageCatalog.codeForDisplay((String)targetSpinner.getSelectedItem());trace.log("UI_TARGET_LANGUAGE",c);translator.setTarget(c);speaker.selectOfflineVoice(c);spokenDiff.reset();translationSeq++;}public void onNothingSelected(android.widget.AdapterView<?> p){}});requestPermissionsIfNeeded();headset.setText(BluetoothRouter.routeToHeadset(this));status.setText(speech.isOnDeviceAvailable()?"Готов к переводу":"Нужно установить офлайн-языки речи в Android");}
    private void requestPermissionsIfNeeded(){List<String> p=new ArrayList<>();if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)p.add(Manifest.permission.RECORD_AUDIO);if(checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED)p.add(Manifest.permission.BLUETOOTH_CONNECT);if(!p.isEmpty())requestPermissions(p.toArray(new String[0]),REQ);}
    @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);headset.setText(BluetoothRouter.routeToHeadset(this));trace.log("PERMISSION_RESULT",java.util.Arrays.toString(g));}
    private void toggle(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissionsIfNeeded();return;}active=!active;trace.log("UI_TOGGLE",active?"start":"stop");if(active){spokenDiff.reset();sourceText.setText("Слушаю…");translatedText.setText("Перевод появится здесь");mainButton.setText("ОСТАНОВИТЬ");headset.setText(BluetoothRouter.routeToHeadset(this));speech.start();}else{speech.stop();speaker.stop();if(pendingTranslation!=null)debounce.removeCallbacks(pendingTranslation);translationSeq++;mainButton.setText("НАЧАТЬ ПЕРЕВОД");status.setText("Остановлено");}}
    @Override public void onText(String text,boolean isFinal,String lang){
        trace.log(isFinal?"UI_FINAL_TEXT":"UI_PARTIAL_TEXT",text+" | lang="+lang); sourceText.setText(text);
        String sourceHint="auto".equals(manualInput)?lang:manualInput;
        if("auto".equals(manualInput)&&lang!=null)detected.setText("Определён язык: "+LanguageCatalog.displayForCode(lang));
        if(pendingTranslation!=null)debounce.removeCallbacks(pendingTranslation);
        final long seq=++translationSeq; final String textSnapshot=text; final String hintSnapshot=sourceHint; final boolean finalSnapshot=isFinal;
        pendingTranslation=()->{trace.log("TRANSLATE_REQUEST","seq="+seq+" hint="+hintSnapshot+" final="+finalSnapshot+" text="+textSnapshot);translator.translateAuto(textSnapshot,hintSnapshot,new TranslationEngine.Callback(){public void onTranslated(String src,String tr){trace.log("TRANSLATE_OK","seq="+seq+" src="+src+" out="+tr);if(seq!=translationSeq){trace.log("TRANSLATE_DROP","stale seq="+seq+" current="+translationSeq);return;}runOnUiThread(()->{if("auto".equals(manualInput))detected.setText("Определён язык: "+LanguageCatalog.displayForCode(src));translatedText.setText(tr);String delta=spokenDiff.acceptPartial(tr,finalSnapshot);trace.log("TTS_DELTA",delta);if(!delta.isBlank())speaker.speak(delta, finalSnapshot);if(finalSnapshot){String tail=spokenDiff.flushFinal(tr);trace.log("TTS_TAIL",tail);if(!tail.isBlank())speaker.speak(tail,true);spokenDiff.reset();}status.setText(finalSnapshot?"Слушаю дальше…":"Перевожу по ходу речи…");});}public void onError(String m){trace.log("TRANSLATE_ERROR","seq="+seq+" "+m);if(seq!=translationSeq)return;runOnUiThread(()->status.setText(m));}});};
        debounce.postDelayed(pendingTranslation,isFinal?0:180);
    }
    @Override public void onStatus(String s){trace.log("SPEECH_STATUS",s);runOnUiThread(()->status.setText(s));} @Override public void onError(String e){trace.log("SPEECH_ERROR",e);runOnUiThread(()->status.setText(e));}
    private void shareTrace(){ try{File f=trace.file();Uri uri=FileProvider.getUriForFile(this,getPackageName()+".fileprovider",f);Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_STREAM,uri);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(i,"Отправить журнал LiveLingo"));}catch(Exception e){Toast.makeText(this,"Не удалось открыть журнал: "+e.getMessage(),Toast.LENGTH_LONG).show();} }
    @Override protected void onDestroy(){if(speech!=null)speech.stop();if(speaker!=null)speaker.close();if(translator!=null)translator.close();super.onDestroy();}
    private void buildUi(){int pad=dp(20);ScrollView scroll=new ScrollView(this);scroll.setBackgroundColor(0xFFF4F5F8);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(pad,dp(24),pad,dp(36));scroll.addView(root);root.addView(tv("LiveLingo",34,true,0xFF0C0D10));root.addView(tv("Синхронный перевод речи",15,false,0xFF747984),lp(-1,-2,0,2,0,22));LinearLayout languageCard=card();languageCard.addView(tv("ЯЗЫК СОБЕСЕДНИКА",11,true,0xFF858B96));inputSpinner=new Spinner(this);inputSpinner.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new ArrayList<>(LanguageCatalog.INPUTS.keySet())));languageCard.addView(inputSpinner,lp(-1,dp(52),0,2,0,12));languageCard.addView(tv("ПЕРЕВОДИТЬ НА",11,true,0xFF858B96));targetSpinner=new Spinner(this);targetSpinner.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new ArrayList<>(LanguageCatalog.TARGETS.keySet())));languageCard.addView(targetSpinner,lp(-1,dp(52),0,2,0,0));root.addView(languageCard,lp(-1,-2,0,0,0,14));detected=tv("Автоопределение языка",14,true,0xFF2D65F2);detected.setGravity(Gravity.CENTER);root.addView(detected,lp(-1,-2,0,0,0,10));mainButton=new Button(this);mainButton.setAllCaps(false);mainButton.setText("НАЧАТЬ ПЕРЕВОД");mainButton.setTextSize(17);mainButton.setTextColor(Color.WHITE);mainButton.setTypeface(Typeface.DEFAULT,Typeface.BOLD);mainButton.setBackground(roundRect(0xFF0C0D10,28));root.addView(mainButton,lp(-1,dp(66),0,0,0,12));status=tv("Готов к переводу",14,true,0xFF363A43);status.setGravity(Gravity.CENTER);root.addView(status,lp(-1,-2,0,0,0,8));headset=tv("",13,false,0xFF858B96);headset.setGravity(Gravity.CENTER);root.addView(headset,lp(-1,-2,0,0,0,18));LinearLayout live=card();live.addView(tv("ОРИГИНАЛ",11,true,0xFF858B96));sourceText=tv("Здесь появится речь собеседника",18,false,0xFF2B2E34);live.addView(sourceText,lp(-1,-2,0,8,0,18));View divider=new View(this);divider.setBackgroundColor(0xFFE8EAF0);live.addView(divider,new LinearLayout.LayoutParams(-1,dp(1)));live.addView(tv("ПЕРЕВОД",11,true,0xFF858B96),lp(-1,-2,0,18,0,0));translatedText=tv("Здесь появится перевод",23,true,0xFF0C0D10);live.addView(translatedText,lp(-1,-2,0,8,0,0));root.addView(live);debugButton=new Button(this);debugButton.setText("ОТПРАВИТЬ ЖУРНАЛ ТЕСТА");debugButton.setAllCaps(false);root.addView(debugButton,lp(-1,dp(50),0,14,0,0));LinearLayout hint=card();hint.addView(tv("⚡ Быстрый режим",14,true,0xFF2D65F2));hint.addView(tv("Если язык собеседника известен, выберите его вручную — распознавание будет точнее и быстрее. Авто оставьте для неизвестного языка.",13,false,0xFF686E79),lp(-1,-2,0,6,0,0));root.addView(hint,lp(-1,-2,0,14,0,0));setContentView(scroll);}
    private LinearLayout card(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(18),dp(18),dp(18),dp(18));l.setBackground(roundRect(0xFFFFFFFF,22));l.setElevation(dp(1));return l;}
    private TextView tv(String t,int sp,boolean bold,int c){TextView v=new TextView(this);v.setText(t);v.setTextSize(sp);v.setTextColor(c);v.setTypeface(Typeface.DEFAULT,bold?Typeface.BOLD:Typeface.NORMAL);return v;}
    private GradientDrawable roundRect(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;} private LinearLayout.LayoutParams lp(int w,int h,int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;} private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
