package com.imagine.livelingo;

import android.Manifest; import android.app.Activity; import android.content.pm.PackageManager; import android.graphics.Color; import android.graphics.Typeface; import android.graphics.drawable.GradientDrawable; import android.os.Bundle; import android.os.Handler; import android.os.Looper; import android.view.Gravity; import android.view.View; import android.widget.*;
import com.imagine.livelingo.core.SpokenDiff; import java.util.ArrayList; import java.util.List;

public class MainActivity extends Activity implements LiveSpeechRecognizer.Listener {
    private static final int REQ=7; private TextView status,sourceText,translatedText,detected,headset; private Button mainButton; private Spinner targetSpinner;
    private LiveSpeechRecognizer speech; private TranslationEngine translator; private OfflineSpeaker speaker; private final SpokenDiff spokenDiff=new SpokenDiff(1); private boolean active;
    private final Handler debounce=new Handler(Looper.getMainLooper()); private Runnable pendingTranslation; private String pendingText="",pendingLanguage=null; private boolean pendingFinal; private long translationSeq=0;
    @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(247,247,250));buildUi();translator=new TranslationEngine();speaker=new OfflineSpeaker(this,s->status.setText(s));speech=new LiveSpeechRecognizer(this,this);mainButton.setOnClickListener(v->toggle());targetSpinner.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){String c=LanguageCatalog.codeForDisplay((String)targetSpinner.getSelectedItem());translator.setTarget(c);speaker.selectOfflineVoice(c);spokenDiff.reset();}public void onNothingSelected(android.widget.AdapterView<?> p){}});requestPermissionsIfNeeded();headset.setText(BluetoothRouter.routeToHeadset(this));status.setText(speech.isOnDeviceAvailable()?"Офлайн-распознавание доступно":"Нужно установить офлайн-языки речи в Android");}
    private void requestPermissionsIfNeeded(){List<String> p=new ArrayList<>();if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)p.add(Manifest.permission.RECORD_AUDIO);if(checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED)p.add(Manifest.permission.BLUETOOTH_CONNECT);if(!p.isEmpty())requestPermissions(p.toArray(new String[0]),REQ);}
    @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);headset.setText(BluetoothRouter.routeToHeadset(this));}
    private void toggle(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissionsIfNeeded();return;}active=!active;if(active){spokenDiff.reset();sourceText.setText("Слушаю речь рядом…");translatedText.setText("Перевод появится здесь");mainButton.setText("ОСТАНОВИТЬ");headset.setText(BluetoothRouter.routeToHeadset(this));speech.start();}else{speech.stop();speaker.stop();if(pendingTranslation!=null)debounce.removeCallbacks(pendingTranslation);translationSeq++;mainButton.setText("НАЧАТЬ ПЕРЕВОД");status.setText("Остановлено");}}
    @Override public void onText(String text,boolean isFinal,String lang){sourceText.setText(text);if(lang!=null)detected.setText("Определён язык: "+LanguageCatalog.displayForCode(lang));pendingText=text;pendingLanguage=lang;pendingFinal=isFinal;if(pendingTranslation!=null)debounce.removeCallbacks(pendingTranslation);final long seq=++translationSeq;final String textSnapshot=text;final String langSnapshot=lang;final boolean finalSnapshot=isFinal;pendingTranslation=()->translator.translateAuto(textSnapshot,langSnapshot,new TranslationEngine.Callback(){public void onTranslated(String src,String tr){if(seq!=translationSeq)return;runOnUiThread(()->{detected.setText("Определён язык: "+LanguageCatalog.displayForCode(src));translatedText.setText(tr);String delta=spokenDiff.acceptPartial(tr,finalSnapshot);if(!delta.isBlank())speaker.speak(delta);if(finalSnapshot)spokenDiff.reset();status.setText(finalSnapshot?"Слушаю дальше…":"Перевожу в реальном времени…");});}public void onError(String m){if(seq!=translationSeq)return;runOnUiThread(()->status.setText(m));}});debounce.postDelayed(pendingTranslation,isFinal?0:120);}
    @Override public void onStatus(String s){runOnUiThread(()->status.setText(s));} @Override public void onError(String e){runOnUiThread(()->status.setText(e));}
    @Override protected void onDestroy(){if(speech!=null)speech.stop();if(speaker!=null)speaker.close();if(translator!=null)translator.close();super.onDestroy();}
    private void buildUi(){int pad=dp(20);ScrollView scroll=new ScrollView(this);scroll.setBackgroundColor(0xFFF7F7FA);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(pad,dp(28),pad,dp(32));scroll.addView(root);root.addView(tv("LiveLingo",32,true,0xFF111216));root.addView(tv("Живой перевод прямо в наушниках",16,false,0xFF666A73),lp(-1,-2,0,4,0,22));LinearLayout mode=card();mode.addView(tv("СЛЫШУ",11,true,0xFF8B8F98));detected=tv("Любой язык · авто",20,true,0xFF111216);mode.addView(detected,lp(-1,-2,0,3,0,14));mode.addView(tv("ПЕРЕВОД",11,true,0xFF8B8F98));targetSpinner=new Spinner(this);targetSpinner.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new ArrayList<>(LanguageCatalog.TARGETS.keySet())));mode.addView(targetSpinner,lp(-1,dp(52),0,0,0,0));root.addView(mode,lp(-1,-2,0,0,0,16));mainButton=new Button(this);mainButton.setAllCaps(false);mainButton.setText("НАЧАТЬ ПЕРЕВОД");mainButton.setTextSize(17);mainButton.setTextColor(Color.WHITE);mainButton.setTypeface(Typeface.DEFAULT,Typeface.BOLD);mainButton.setBackground(roundRect(0xFF111216,28));root.addView(mainButton,lp(-1,dp(64),0,0,0,16));status=tv("Проверяю телефон…",14,true,0xFF3B3E45);status.setGravity(Gravity.CENTER);root.addView(status,lp(-1,-2,0,0,0,10));headset=tv("",13,false,0xFF777B84);headset.setGravity(Gravity.CENTER);root.addView(headset,lp(-1,-2,0,0,0,20));LinearLayout card=card();card.addView(tv("ОРИГИНАЛ",11,true,0xFF8B8F98));sourceText=tv("Здесь появится речь собеседника",18,false,0xFF2E3036);card.addView(sourceText,lp(-1,-2,0,8,0,20));card.addView(tv("ПЕРЕВОД",11,true,0xFF8B8F98));translatedText=tv("Здесь появится перевод",22,true,0xFF111216);card.addView(translatedText,lp(-1,-2,0,8,0,0));root.addView(card);root.addView(tv("Первый запуск каждого языка загружает модель. После этого перевод работает локально и без оплаты за минуты.",13,false,0xFF777B84),lp(-1,-2,0,18,0,0));setContentView(scroll);}
    private LinearLayout card(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(18),dp(18),dp(18),dp(18));l.setBackground(roundRect(0xFFFFFFFF,22));l.setElevation(dp(1));return l;}
    private TextView tv(String t,int sp,boolean bold,int c){TextView v=new TextView(this);v.setText(t);v.setTextSize(sp);v.setTextColor(c);v.setTypeface(Typeface.DEFAULT,bold?Typeface.BOLD:Typeface.NORMAL);return v;}
    private GradientDrawable roundRect(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;} private LinearLayout.LayoutParams lp(int w,int h,int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;} private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
