package com.imagine.livelingo;

import android.Manifest; import android.app.Activity; import android.content.pm.PackageManager; import android.graphics.Color; import android.graphics.Typeface; import android.graphics.drawable.GradientDrawable; import android.os.Bundle; import android.os.Handler; import android.os.Looper; import android.view.Gravity; import android.view.View; import android.widget.*;
import com.imagine.livelingo.core.SpokenDiff; import java.util.ArrayList; import java.util.List;

public class MainActivity extends Activity implements LiveSpeechRecognizer.Listener {
    private static final int REQ=7; private TextView status,sourceText,translatedText,detected,headset; private Button mainButton; private Spinner inputSpinner,targetSpinner;
    private LiveSpeechRecognizer speech; private TranslationEngine translator; private OfflineSpeaker speaker; private final SpokenDiff spokenDiff=new SpokenDiff(2); private boolean active;
    private final Handler debounce=new Handler(Looper.getMainLooper()); private Runnable pendingTranslation; private long translationSeq=0; private String manualInput="auto";
    @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(0xFFF4F5F8);buildUi();translator=new TranslationEngine();speaker=new OfflineSpeaker(this,s->status.setText(s));speech=new LiveSpeechRecognizer(this,this);mainButton.setOnClickListener(v->toggle());inputSpinner.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){manualInput=LanguageCatalog.inputCodeForDisplay((String)inputSpinner.getSelectedItem());speech.setInputLanguage(manualInput);detected.setText("auto".equals(manualInput)?"Автоопределение языка":"Говорит: "+LanguageCatalog.displayForCode(manualInput));spokenDiff.reset();translationSeq++;}public void onNothingSelected(android.widget.AdapterView<?> p){}});targetSpinner.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){String c=LanguageCatalog.codeForDisplay((String)targetSpinner.getSelectedItem());translator.setTarget(c);speaker.selectOfflineVoice(c);spokenDiff.reset();translationSeq++;}public void onNothingSelected(android.widget.AdapterView<?> p){}});requestPermissionsIfNeeded();headset.setText(BluetoothRouter.routeToHeadset(this));status.setText(speech.isOnDeviceAvailable()?"Готов к переводу":"Нужно установить офлайн-языки речи в Android");}
    private void requestPermissionsIfNeeded(){List<String> p=new ArrayList<>();if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)p.add(Manifest.permission.RECORD_AUDIO);if(checkSelfPermission(Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED)p.add(Manifest.permission.BLUETOOTH_CONNECT);if(!p.isEmpty())requestPermissions(p.toArray(new String[0]),REQ);}
    @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);headset.setText(BluetoothRouter.routeToHeadset(this));}
    private void toggle(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissionsIfNeeded();return;}active=!active;if(active){spokenDiff.reset();sourceText.setText("Слушаю…");translatedText.setText("Перевод появится здесь");mainButton.setText("ОСТАНОВИТЬ");headset.setText(BluetoothRouter.routeToHeadset(this));speech.start();}else{speech.stop();speaker.stop();if(pendingTranslation!=null)debounce.removeCallbacks(pendingTranslation);translationSeq++;mainButton.setText("НАЧАТЬ ПЕРЕВОД");status.setText("Остановлено");}}
    @Override public void onText(String text,boolean isFinal,String lang){
        sourceText.setText(text);
        String sourceHint="auto".equals(manualInput)?lang:manualInput;
        if("auto".equals(manualInput)&&lang!=null)detected.setText("Определён язык: "+LanguageCatalog.displayForCode(lang));
        if(pendingTranslation!=null)debounce.removeCallbacks(pendingTranslation);
        final long seq=++translationSeq; final String textSnapshot=text; final String hintSnapshot=sourceHint; final boolean finalSnapshot=isFinal;
        pendingTranslation=()->translator.translateAuto(textSnapshot,hintSnapshot,new TranslationEngine.Callback(){public void onTranslated(String src,String tr){if(seq!=translationSeq)return;runOnUiThread(()->{if("auto".equals(manualInput))detected.setText("Определён язык: "+LanguageCatalog.displayForCode(src));translatedText.setText(tr);String delta=spokenDiff.acceptPartial(tr,finalSnapshot);if(!delta.isBlank())speaker.speak(delta, finalSnapshot);if(finalSnapshot){String tail=spokenDiff.flushFinal(tr);if(!tail.isBlank())speaker.speak(tail,true);spokenDiff.reset();}status.setText(finalSnapshot?"Слушаю дальше…":"Перевожу по ходу речи…");});}public void onError(String m){if(seq!=translationSeq)return;runOnUiThread(()->status.setText(m));}});
        debounce.postDelayed(pendingTranslation,isFinal?0:180);
    }
    @Override public void onStatus(String s){runOnUiThread(()->status.setText(s));} @Override public void onError(String e){runOnUiThread(()->status.setText(e));}
    @Override protected void onDestroy(){if(speech!=null)speech.stop();if(speaker!=null)speaker.close();if(translator!=null)translator.close();super.onDestroy();}
    private void buildUi(){int pad=dp(20);ScrollView scroll=new ScrollView(this);scroll.setBackgroundColor(0xFFF4F5F8);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(pad,dp(24),pad,dp(36));scroll.addView(root);root.addView(tv("LiveLingo",34,true,0xFF0C0D10));root.addView(tv("Синхронный перевод речи",15,false,0xFF747984),lp(-1,-2,0,2,0,22));LinearLayout languageCard=card();languageCard.addView(tv("ЯЗЫК СОБЕСЕДНИКА",11,true,0xFF858B96));inputSpinner=new Spinner(this);inputSpinner.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new ArrayList<>(LanguageCatalog.INPUTS.keySet())));languageCard.addView(inputSpinner,lp(-1,dp(52),0,2,0,12));languageCard.addView(tv("ПЕРЕВОДИТЬ НА",11,true,0xFF858B96));targetSpinner=new Spinner(this);targetSpinner.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new ArrayList<>(LanguageCatalog.TARGETS.keySet())));languageCard.addView(targetSpinner,lp(-1,dp(52),0,2,0,0));root.addView(languageCard,lp(-1,-2,0,0,0,14));detected=tv("Автоопределение языка",14,true,0xFF2D65F2);detected.setGravity(Gravity.CENTER);root.addView(detected,lp(-1,-2,0,0,0,10));mainButton=new Button(this);mainButton.setAllCaps(false);mainButton.setText("НАЧАТЬ ПЕРЕВОД");mainButton.setTextSize(17);mainButton.setTextColor(Color.WHITE);mainButton.setTypeface(Typeface.DEFAULT,Typeface.BOLD);mainButton.setBackground(roundRect(0xFF0C0D10,28));root.addView(mainButton,lp(-1,dp(66),0,0,0,12));status=tv("Готов к переводу",14,true,0xFF363A43);status.setGravity(Gravity.CENTER);root.addView(status,lp(-1,-2,0,0,0,8));headset=tv("",13,false,0xFF858B96);headset.setGravity(Gravity.CENTER);root.addView(headset,lp(-1,-2,0,0,0,18));LinearLayout live=card();live.addView(tv("ОРИГИНАЛ",11,true,0xFF858B96));sourceText=tv("Здесь появится речь собеседника",18,false,0xFF2B2E34);live.addView(sourceText,lp(-1,-2,0,8,0,18));View divider=new View(this);divider.setBackgroundColor(0xFFE8EAF0);live.addView(divider,new LinearLayout.LayoutParams(-1,dp(1)));live.addView(tv("ПЕРЕВОД",11,true,0xFF858B96),lp(-1,-2,0,18,0,0));translatedText=tv("Здесь появится перевод",23,true,0xFF0C0D10);live.addView(translatedText,lp(-1,-2,0,8,0,0));root.addView(live);LinearLayout hint=card();hint.addView(tv("⚡ Быстрый режим",14,true,0xFF2D65F2));hint.addView(tv("Если язык собеседника известен, выберите его вручную — распознавание будет точнее и быстрее. Авто оставьте для неизвестного языка.",13,false,0xFF686E79),lp(-1,-2,0,6,0,0));root.addView(hint,lp(-1,-2,0,14,0,0));setContentView(scroll);}
    private LinearLayout card(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(18),dp(18),dp(18),dp(18));l.setBackground(roundRect(0xFFFFFFFF,22));l.setElevation(dp(1));return l;}
    private TextView tv(String t,int sp,boolean bold,int c){TextView v=new TextView(this);v.setText(t);v.setTextSize(sp);v.setTextColor(c);v.setTypeface(Typeface.DEFAULT,bold?Typeface.BOLD:Typeface.NORMAL);return v;}
    private GradientDrawable roundRect(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;} private LinearLayout.LayoutParams lp(int w,int h,int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;} private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}
}
